### ISSUE TITLE
Original data of the dataset

### ISSUE THREAD

**Issue by hblflybird** [weihaox/interpGaze#1]
Thanks for your excellent work, could you please share the original data of the dataset?

**Comment by weihaox** [comment]
Thank you for the concern of our work. The [link](https://drive.google.com/drive/folders/19m9aNbVtk9eBX_4eO_7XItXR_2tjYJPo) of the full images is updated. We have shared the front head pose of 37 subjects. The others are not released due to the privacy policy.
